# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test release CI with gradle

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: deploy

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: gradlew 권한 변경
      working-directory: ./back/babble
      run: chmod +x gradlew

    - name: 빌드 진행
      working-directory: ./back/babble
      run: ./gradlew clean build

    - name: SCP 명령을 이용해 테스트용 서버로 jar 파일 전송
      working-directory: ./back/babble
      run: scp ./build/libs/babble-0.0.1-SNAPSHOT.jar test:/home/ubuntu/was

    - name: SSH 명령을 통해 테스트용 서버 접속 후 jar 파일 실행
      run: ssh test "cd was; /home/ubuntu/was/deploy.sh;"

#       run: ssh was "mv /home/ubuntu/babble-0.0.1-SNAPSHOT.jar /home/ubuntu/deploy; sudo docker build -t babble/was /home/ubuntu/deploy; sudo docker run -d -p 8080:8080 babble/was;"
#     run: nohup java -jar -Dspring.profiles.active=prod ./build/libs/atdd-subway-fare-0.0.1-SNAPSHOT.jar 1> ./logs/error.log 2>&1 &


# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: 빌드
        working-directory: ./front
        run: npm run build
      
      - name: 배포
        working-directory: ./front
        run: aws s3 sync ./dist s3://bucket-babble-front/
      